### PR TITLE
Cocotb APIs and netlist

### PR DESCRIPTION
**Pull request by M0stafaRady**
1. Update  C APIs to clear interrupt when disable an interrupt 
2. Remove caravel_core from gate level netlist as the user should get it after running [gen_gpio_defaults](https://github.com/efabless/caravel/blob/main/scripts/gen_gpio_defaults.py)  and include it in the user includes.

### CODE REVIEW

**Comment by marwaneltoukhy** [comment]
1. Is it documented that the user needs to run `gen_gpio_defaults` script?
2. Shouldn't the `caravel_core` be included in the user's includes?
3. I think you can run the `gen_gpio_defaults` script as part of the verification make target for gl

**Comment by M0stafaRady** [comment]
> 1. Is it documented that the user needs to run `gen_gpio_defaults` script?

I'm not aware if it is documented somewhere.

> 2. Shouldn't the `caravel_core` be included in the user's includes?

Yes, That's true. That's why the PR remove them from caravel netlist

> 3. I think you can run the `gen_gpio_defaults` script as part of the verification make target for gl
Maybe, this a good idea. 

This PR also contains some changes related to the APIs which needed to be merged.

**Comment by marwaneltoukhy** [comment]
It needs to be documented that in order to run the gl verification the users need to run `gen_gpio_defaults`, and you can add running the script in the Make target in order to run it automatically when a user runs the gl verification.

**Comment by M0stafaRady** [comment]
Documentation added here : https://github.com/efabless/caravel_user_project/pull/309

**Review by jeffdi — APPROVED** [review]

**Pull request merged**
