### PR TITLE
Wishbone test

### PR DESCRIPTION
**Pull request by suppamax**
Issue #24

### CODE REVIEW

**Review by marwaneltoukhy — COMMENTED** [review]
please rebase from wb_slave_address_fix branch

**Comment by marwaneltoukhy** [comment]
Tried this out with the fix in wb_slave_address_fix branch, and both RTL and GL failed

**Comment by suppamax** [comment]
According to #24 the size of the wishbone area is 0x10000000, but in the `wb_slave_address_fix` branch it is only 0x1000000
https://github.com/efabless/caravel_mgmt_soc_litex/blob/48361c7a87a15afed43cd5a89a554bb1d7be442e/litex/caravel.py#L186
The test has been adapted to be compatible with the branch, but I am not sure it is what you really want.

**Comment by marwaneltoukhy** [comment]
Thank you everyone for your efforts on this. At this time, due to the age of this issue and other changes that have happened since, we have decided to close this PR without merging it. In some cases this also means there is now a better or other recommended approach, or possible the PR otherwise relates to a deprecated mode of use. Reviewed by @marwaneltoukhy @DavidRLindley

**Pull request closed without merging**
