### PR TITLE
 new environment for simulation automation with cocotb and vcs 

### PR DESCRIPTION
**Pull request by M0stafaRady**
This pull request is completing the following [pull request](https://github.com/efabless/caravel/pull/139)  in caravel repo

### CODE REVIEW

**Review by marwaneltoukhy — CHANGES_REQUESTED** [review]
I don't understand this PR, looks like there's no automation of any kind and there is no documentation on how to run the automation.

**Comment by M0stafaRady** [comment]
Please check the pull request with the same title in caravel repo they are completing each other.

**Comment by marwaneltoukhy** [comment]
Please write that in the PR description and link to the other PR

**Comment by marwaneltoukhy** [comment]
Looks fine and works fine for me.

**Review by marwaneltoukhy — APPROVED** [review]

**Review by marwaneltoukhy — APPROVED** [review]

**Pull request merged**
